#!/bin/bash
CONTENTS="$( cd "$( dirname "$0" )/.." && pwd )"
JAVA="$(find $CONTENTS/PlugIns -maxdepth 1 -type d -name '*jdk')/Contents/Home/jre/bin/java"
APPDIR="$CONTENTS/Processing"
$JAVA -Djna.nosys=true -Djava.library.path="$APPDIR:$APPDIR/lib:$APPDIR/lib/jycessing" -ea -cp "$APPDIR/lib/jycessing/PythonMode.jar:$APPDIR/lib/jycessing/gluegen-rt-natives-macosx-universal.jar:$APPDIR/lib/jycessing/jogl-all.jar:$APPDIR/lib/jycessing/gluegen-rt.jar:$APPDIR/lib/jycessing/core.jar:$APPDIR/lib/jycessing/jogl-all-natives-macosx-universal.jar:$APPDIR/lib/jycessing/jython.jar:$APPDIR/lib/jycessing/guava-17.0.jar" -splash:"$APPDIR/lib/jycessing/splash.png" -Xdock:icon="$CONTENTS/Resources/sketch.icns" -Xdock:name="ESP32_GUI_Programmer" jycessing.Runner --noredirect --exported --hide-stop "$APPDIR/source/ESP32_GUI_Programmer.pyde"
